#-----------set_ups-------------------
REQUEST_LOGIN = '0001' # LOGIN REQUEST
REQUEST_CHAT = '0002' # CHATTING  REQUEST
RESPONSE_LOGIN_REQUEST = '1001' # RESPOND TO LOG IN
RESPONSE_CHAT_REQUEST = "1002" #RESPOND TO CHATTING
DELIMITER = "|"
